version: '3'
services:
    #PHP Service
    app-votecipa:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app-votecipa
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/8.1
        networks:
            - api-app_default
    #Nginx Service
    webserver:
        image: nginx:stable-alpine
        container_name: webserver-votecipa
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - api-app_default
    #MySQL Service
    db:
        image: mariadb:10.5.8
        command: "--innodb_use_native_aio=0"
        container_name: mysql-votecipa
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ../cms-message-center/.docker/banco:/var/lib/mysql
            - ../cms-message-center/.docker/mysql/my.cnf:/etc/mysql/mycnf
        networks:
            - api-app_default
#Networks
networks:
    api-app_default:
        external: true
